link: 'https://ucloud.univie.ac.at/index.php/s/wEp8nwSy7kQ8ZHz/download/snakemake_rnaseq.tar.gz'
conditions:
  - 'highCO2'
  - 'lowCO2'
samples:
  - 'sample1'
  - 'sample2'
  - 'sample3'
mates:
  - '1'
  - '2'
max_threads: 8




